# Generated by Django 2.0.7 on 2018-09-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontuacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadealuno',
            name='agilidade',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atividadealuno',
            name='perfeccionismo',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atividadealuno',
            name='precisao',
            field=models.NullBooleanField(default=False),
        ),
    ]
