# Generated by Django 2.0.7 on 2018-09-21 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfeccionismo', models.BooleanField(default=False)),
                ('agilidade', models.BooleanField(default=False)),
                ('precisao', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Pessoa')),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pontuacoes.Atividade')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='alunos',
            field=models.ManyToManyField(through='pontuacoes.AtividadeAluno', to='core.Pessoa'),
        ),
    ]
