# Generated by Django 2.0.7 on 2018-09-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pontuacoes', '0003_auto_20180921_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='alunos',
            field=models.ManyToManyField(through='pontuacoes.AtividadeAluno', to='core.Aluno'),
        ),
        migrations.AlterField(
            model_name='atividadealuno',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Aluno'),
        ),
    ]
